---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv4
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-k83"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0eadcb1365d90d767 #ebs-k82
