---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv4
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-k83"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com # aws-ebs-csi-driver
    volumeHandle: vol-0eadcb1365d90d767 #ebs-k82

    #pv.yaml
#Ref: https://aws.amazon.com/blogs/storage/persistent-storage-for-kubernetes/,  https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html
