apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: <Password> #Password no longer needs to be base64 encrypted


  #in your deployment yaml file, under the container's block, use the enviromental variable to reference secret
  #env:
     # - name: SECRET_USERNAME
      #  valueFrom:
       #   secretKeyRef:
        #    name: mysecret
         #   key: username
          #  optional: false # same as default; "mysecret" must exist
           #                 # and include a key named "username"
     # - name: SECRET_PASSWORD
      #  valueFrom:
       #   secretKeyRef:
        #    name: mysecret
         #   key: password
          #  optional: false # same as default; "mysecret" must exist
                            # and include a key named "password"
