#pv.yaml
#Ref: https://aws.amazon.com/blogs/storage/persistent-storage-for-kubernetes/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 12Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-sc"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com #add aws-efs-csi-driver try this as well  
    volumeHandle: fs-0255d01dc40e2392e #create file system first then use the id here
