---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: springapp-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
